###
GET http://localhost:8080/thread

### Get Single Thread
GET http://localhost:8080/thread/667cd0ec63a3a699eff71aec


### Get threads by Author
GET http://localhost:8080/thread/author/Gwillis



### Post a thread
POST http://localhost:8080/thread HTTP/1.1
Content-Type: application/json

 {
  "title": "The Remnant's Hope",
  "author": "Grant William Willis",
  "publishedDate": "2023-08-15",
  "content": "Jeck knew he had over done it this time.... ",
  "tags": ["mystery", "fantasy"],
  "metadata": {
    "wordCount": 1500,
    "genre": "Fantasy/Science-Fiction"
  }
}

### Update a Thread
PUT  http://localhost:8080/thread/667cd0ec63a3a699eff71aec HTTP/1.1
Content-Type: application/json

{
    "title": "The Remnant's Hope",
    "author": "Grant William Willis",
    "publishedDate": "2023-08-15",
    "content": "Jeck knew he had over done it this time.... ",
    "tags": [
      "mystery",
      "adventure",
      "romance",
      "fantasy"
    ],
    "metadata": {
      "wordCount": 1500,
      "genre": "Fantasy/Science-Fiction"
    }
}

###
GET http://fableforge.onrender.com/thread

### Get ALL threads via Render
GET https://fableforge-ouvx.onrender.com/thread

### Get threads by Author
GET https://fableforge-ouvx.onrender.com/thread/author/Gwillis


### Update thread via render

PUT http://fableforge.onrender.com/thread/id